# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  awakened-poe-trade = {
    pname = "awakened-poe-trade";
    version = "3.27.105";
    src = fetchurl {
      url = "https://github.com/SnosMe/awakened-poe-trade/releases/download/v3.27.105/Awakened-PoE-Trade-3.27.105.AppImage";
      sha256 = "sha256-XEnxDo8Njt/r7tmRxbKMNKqG/YUlc59TJY/7mjiOyXE=";
    };
  };
  vivid-plasma-themes = {
    pname = "vivid-plasma-themes";
    version = "cc20e7b72c2e9c05d7a7a5345f85eb4eba20e565";
    src = fetchgit {
      url = "https://github.com/L4ki/Vivid-Plasma-Themes.git";
      rev = "cc20e7b72c2e9c05d7a7a5345f85eb4eba20e565";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-gAD7C7vOEI4yL+eX1410f/VkfQQ7t+oreypaU+Md1Vc=";
    };
    date = "2025-11-24";
  };
}
