# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  exiled-exchange-2 = {
    pname = "exiled-exchange-2";
    version = "0.13.10";
    src = fetchurl {
      url = "https://github.com/Kvan7/Exiled-Exchange-2/releases/download/v0.13.10/Exiled-Exchange-2-0.13.10.AppImage";
      sha256 = "sha256-mQNUJptaObbEMtBLCgJn7A6nmgVpl4o0JWTg6FH20U0=";
    };
  };
  niri = {
    pname = "niri";
    version = "b07bde3ee82dd73115e6b949e4f3f63695da35ea";
    src = fetchFromGitHub {
      owner = "YaLTeR";
      repo = "niri";
      rev = "b07bde3ee82dd73115e6b949e4f3f63695da35ea";
      fetchSubmodules = false;
      sha256 = "sha256-3bwx4WqCB06yfQIGB+OgIckOkEDyKxiTD5pOo4Xz2rI=";
    };
    date = "2026-03-10";
  };
  tdarr-node = {
    pname = "tdarr-node";
    version = "2.64.02";
    src = fetchurl {
      url = "https://storage.tdarr.io/versions/2.64.02/linux_x64/Tdarr_Node.zip";
      sha256 = "sha256-o6nqeJAzXWSkIoYJFeoqPsHHrNGqKzuyF0NPivDQnSg=";
    };
  };
  vivid-plasma-themes = {
    pname = "vivid-plasma-themes";
    version = "598e24d41b1a040620e81e971020e32fa9480944";
    src = fetchgit {
      url = "https://github.com/L4ki/Vivid-Plasma-Themes.git";
      rev = "598e24d41b1a040620e81e971020e32fa9480944";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Qr3NYqtjdlULRPzPw0N8ff6feAGpN63/PB2hm+srylM=";
    };
    date = "2026-01-29";
  };
}
